use_frameworks!

target 'SILame_Example' do
  pod 'SILame', :path => '../', :configurations => ['Debug']


  target 'SILame_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
